---
title: "Task 4: 营销模型——变量衍生"
output: html_notebook
---

营销模型的建立主要是为了研究用户与其是否响应营销之间的关系，在本数据中，营销活动于1998年7月1号开始，我们设定观察期为营销活动开始前的半年时间，即从1998年1月1日到1998年6月30日。下面开始构造营销模型中的自变量X。

人口特征和社会经济特征在客户表中已经给出，我们将重点放在构造交易特征和余额特征上。

## 构造交易特征
```{r}
trans_obj <- trans_obj %>% select(-c(k_symbol, account, bank, trans_id)) 
```

```{r}
# trans_obj是合法交易用户在1998-01-01至1998-06-30之间进行的所有交易数据
trans_summ <- trans_obj %>% group_by(account_id, operation) %>% 
  mutate(Freq = n(), Amnt_Sum = sum(amount_num), 
         Amnt_Avg = mean(amount_num), Amnt_Std = sd(amount_num), 
         Amnt_Max = max(amount_num), Amnt_Min = min(amount_num), 
         Amnt_Rng = Amnt_Max - Amnt_Min)  %>% ungroup(operation) %>%
  mutate(Cur_blnc = balance_num[which.max(date)], 
         Avg_blnc = mean(balance_num),
         Std_blnc = sd(balance_num),
         Max_blnc = max(balance_num),
         Min_blnc = min(balance_num),
         Rng_blnc = Max_blnc - Min_blnc) %>%
  select(-c(date, type, amount_num, balance_num))


trans_summ <- trans_summ[!duplicated(trans_summ), ] 

df <- trans_summ %>% 
  summarise(Num_oper = n(), Most_oper = operation[which.max(Amnt_Freq)], .groups = "drop")

operation <- unique(trans_obj$operation)
for (op in operation) {
  assign(paste0("summ_", op), trans_summ[trans_summ$operation == op, ])
}

colnames(summ_loan) <- c("account_id", "operation", paste0("Loan_", colnames(summ_loan)[3:15]))
colnames(summ_cash) <- c("account_id", "operation", paste0("Cash_", colnames(summ_cash)[3:15]))
colnames(summ_cc_debit)<- c("account_id", "operation", paste0("Debit_", colnames(summ_cc_debit)[3:15]))
colnames(summ_collection) <- c("account_id", "operation", paste0("Cllct_", colnames(summ_collection)[3:15]))
colnames(summ_remit) <- c("account_id", "operation", paste0("Remit_", colnames(summ_remit)[3:15]))
colnames(summ_) <- c("account_id", "operation", paste0("unk_", colnames(summ_)[3:15]))

summ_loan       <- select(summ_loan, -operation)
summ_cash       <- select(summ_cash, -operation)
summ_cc_debit   <- select(summ_cc_debit, -operation)
summ_collection <- select(summ_collection, -operation)
summ_remit      <- select(summ_remit, -operation)
summ_           <- select(summ_, -operation)
  
trans_fea <- full_join(summ_loan, summ_cash, by="account_id") %>% full_join(summ_cc_debit, by = "account_id") %>%
  full_join(summ_collection, by = "account_id") %>% full_join(summ_remit, by = "account_id") %>%
  full_join(summ_, by = "account_id") 

trans_fea$Num_oper <- df[["Num_oper"]]
trans_fea$Most_oper <- df[["Most_oper"]]


````